### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by skynet-devel** [skynet-devel/arch-install#1]
# TODO
### Tasks:

**Priority 1:**

- [ ] Finish integration of install mode:   LUKS on LVM
- [ ] Selectable root-volume size
- [ ] Better UI size for smaller screen resulutions
- [ ] Selctable locale

**Priority 2:**

- [ ] Detect avaiable packets for linux-kernel automatically
- [ ] Use other languages for GRUB menu

		How to tell GRUB to use selected language for grub menu ???
		After first installation do 'grub-mkconfig -o /boot/grub/grub.cfg' again and it will work.
		Try to set locale environment variables (e.g. $LANG) in installation script bevore GRUB installation doesn´t work.

- [ ] Add configurated temp filesystem
- [ ] Check partition names for partitioning (with blanks?)
- [ ] Wipe LUKS header bevore partitioning?
- [ ] Install yaourt
- [ ] Integrate partitionscheme overview
- [ ] Create featurelist Markdown file

### Check arch-installer quality:

* Maximum verbosity for every installation step!

### New features:

- [ ] Qualitycheck for passwords
- [ ] Installationlog
- [ ] Color for UI
- [ ] Installation mode:	Plain dm-crypt (Full disk encrytion)
* Make selectable:
	- [ ] Bootloader (Grub, systemd, ...)
	- [ ] Timesync (ntp, systemd, ...)
	- [ ] Filesystem (ext4, btrfs, zfs, ...)
	- [ ] Standarteditor (nano, vi, vim, emacs, gedit ...)

### Successfully tested:

Install-modes:

* LVM
* LVM on LUKS
